version: '3'

services:
  app:
    build: .
    image: base-java:latest
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - "data:/data"
    environment:
      SPRING_PROFILES_ACTIVE: dev

volumes:
  data:
